spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test_example
    username: root
    password: 123456

  liquibase:
    url: jdbc:mysql://localhost:3307/test_example
    user: root
    password: 123456
    change-log: "classpath:/db/changelog/changelog-master.yaml"
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
